version: 2

models:
  - name: fact_taxi_trips
    description: "fact table"
    columns:
      - name: trip_id
        description: "Fact table primary key"
        tests:
          - not_null
          - unique    
      - name: taxi_id
        description: "Identifier for taxi"
      - name: year
      - name: month
      - name: trip_minutes
        description: "taxi ride in minutes"
      - name: trip_miles
        description: "The distance traveled in miles"
      - name: pickup_census_tract
        tests:
          - relationships:
              to: ref('dim_pickup')
              field: pickup_census_tract
      - name: dropoff_census_tract
        tests:
          - relationships:
              to: ref('dim_dropoff')
              field: dropoff_census_tract
      - name: payment_type
        description: "The type of payment used by the passenger"
      - name: fare
        description: "The time-and-distance fare calculated by the meter"
      - name: tips
        description: ""This field is automatically populated for credit card tips""
      - name: extras
        description: "$0.30 improvement surcharge assessed trips at the flag drop. The improvement surcharge began being levied in 2015."
      - name: trip_total
        description: "Total amount charged to passengers, not include cash tips"

  - name: dim_dropoff
    description: "drop off"
    columns:
    - name: dropoff_census_tract
      tests:
        - unique
        - not_null
    columns:
    - name: dropoff_community_area
      tests:
        - not_null

  - name: dim_fare_company
    description: "average fare for each company"
    columns:
    - name: company
      tests:
        - not_null
    - name: trip_miles
      test:
       - not_null
    